//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTestProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int ID { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Student { get; set; }
        public string Subjects { get; set; }
        public Nullable<double> Obtained_marks { get; set; }
        public Nullable<double> Total_marks { get; set; }
        public Nullable<System.DateTime> Exam_date { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual Student Student1 { get; set; }
    }
}
