//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTestProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int ID { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Subject { get; set; }
        public string Title { get; set; }
        public string Option_a { get; set; }
        public string Option_b { get; set; }
        public string Option_c { get; set; }
        public string Option_d { get; set; }
        public string Solution { get; set; }
        public string Correct_ans { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual Subject Subject1 { get; set; }
    }
}
